### ISSUE TITLE
1.14.4 not working with dedicated server

### ISSUE THREAD

**Issue by The-M1k3y** [Buuz135/Portality#58]
Hi,

the Mod is not working on a dedicated server running Minecraft 1.14.4. The Portal Controller opens no GUI and the server throws an error when trying to access the controller with an incomplete portal (also no text is shown on the client).

Error when accessing incomplete portal:

> [15:53:10]` [Server thread/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/resources/I18n for invalid dist DEDICATED_SERVER
[15:53:10] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
java.lang.RuntimeException: Attempted to load class net/minecraft/client/resources/I18n for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClass(RuntimeDistCleaner.java:71) ~[forge-1.14.4-28.1.1.jar:28.1] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:69) ~[modlauncher-3.2.0.jar:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:114) ~[modlauncher-3.2.0.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:236) ~[modlauncher-3.2.0.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:127) ~[modlauncher-3.2.0.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:97) ~[modlauncher-3.2.0.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212] {}
        at com.buuz135.portality.block.BlockController.func_220051_a(BlockController.java:103) ~[?:?] {}
        at net.minecraft.block.BlockState.func_215687_a(BlockState.java:274) ~[?:?] {pl:runtimedistcleaner:A}
        at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:322) ~[?:?] {}
        at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:847) ~[?:?] {}
        at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?] {}
        at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?] {}
        at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?] {pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?] {}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?] {pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?] {pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:679) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] {}

This looks related to the problem described in https://github.com/InnovativeOnlineIndustries/Portality/issues/45 and https://github.com/InnovativeOnlineIndustries/Portality/issues/48

Tried with forge 28.0.55 with Mod-Version 2.0.14 and 2.0.0-5f9c6a1 and with forge 28.1.1 and Mod-version 2.0.0-5f9c6a1

**Comment by Buuz135** [comment]
Fixed in released version 2.0.4
