### ISSUE TITLE
1.14.4 Crash on game load w Forge 28.1

### ISSUE THREAD

**Issue by Knito58** [Buuz135/Portality#59]
Game does not start, loader crashes.
https://pastebin.com/A6gDCKgi

MC 1.14.4, Forge 28.1.1, Portality 2.0.0-5f9c6a1

**Comment by Knito58** [comment]
```
Caused by: net.minecraftforge.fml.ModLoadingException: Portality has class loading errors
ยง7Failed to load hierarchy member com/hrznstudio/titanium/module/ModuleController
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:77) ~[?:28.1] {}
	at sun.reflect.GeneratedConstructorAccessor23.newInstance(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[?:28.1] {}

```
... also with Forge 28.1.10

**Comment by adrwa** [comment]
You need to install titanium https://www.curseforge.com/minecraft/mc-mods/titanium

**Comment by Knito58** [comment]
Thank you and I'm sorry for that.
