### ISSUE TITLE
[bug] Fluid Module doesn't work

### ISSUE THREAD

**Issue by asimenio-asteri** [Buuz135/Portality#67]
Exactly what the title says, and when you click on the button in the bottom left of the fluid module UI, the entire game crashes with this log: 
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 1/3/20 2:10 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at com.hrznstudio.titanium.block.tile.TileActive.getHandlerFromName(TileActive.java:211) ~[?:2.2.9] {re:classloading}
	at com.hrznstudio.titanium.client.gui.addon.FacingHandlerGuiAddon$1.getState(FacingHandlerGuiAddon.java:148) ~[?:2.2.9] {re:classloading}
	at com.hrznstudio.titanium.client.gui.addon.StateButtonAddon.getStateInfo(StateButtonAddon.java:58) ~[?:2.2.9] {re:classloading}
	at com.hrznstudio.titanium.client.gui.addon.StateButtonAddon.drawGuiContainerBackgroundLayer(StateButtonAddon.java:32) ~[?:2.2.9] {re:classloading}
	at com.hrznstudio.titanium.client.gui.container.GuiContainerBase.lambda$drawGuiContainerBackgroundLayer$0(GuiContainerBase.java:83) ~[?:2.2.9] {re:classloading}
	at com.hrznstudio.titanium.client.gui.container.GuiContainerBase$$Lambda$10493/993537062.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {}
	at com.hrznstudio.titanium.client.gui.container.GuiContainerBase.func_146976_a(GuiContainerBase.java:76) ~[?:2.2.9] {re:classloading}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.render(ContainerScreen.java:75) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:355) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:890) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.1.106.jar:28.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$419/619621481.call(Unknown Source) [forge-1.14.4-28.1.106.jar:28.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.hrznstudio.titanium.block.tile.TileActive.getHandlerFromName(TileActive.java:211)
	at com.hrznstudio.titanium.client.gui.addon.FacingHandlerGuiAddon$1.getState(FacingHandlerGuiAddon.java:148)
	at com.hrznstudio.titanium.client.gui.addon.StateButtonAddon.getStateInfo(StateButtonAddon.java:58)
	at com.hrznstudio.titanium.client.gui.addon.StateButtonAddon.drawGuiContainerBackgroundLayer(StateButtonAddon.java:32)
	at com.hrznstudio.titanium.client.gui.container.GuiContainerBase.lambda$drawGuiContainerBackgroundLayer$0(GuiContainerBase.java:83)
	at com.hrznstudio.titanium.client.gui.container.GuiContainerBase$$Lambda$10493/993537062.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.hrznstudio.titanium.client.gui.container.GuiContainerBase.func_146976_a(GuiContainerBase.java:76)
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.render(ContainerScreen.java:75)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:355)

-- Screen render details --
Details:
	Screen name: com.hrznstudio.titanium.client.gui.container.GuiContainerTileBase
	Mouse location: Scaled: (271, 171). Absolute: (543.000000, 343.000000)
	Screen size: Scaled: (683, 353). Absolute: (1366, 705). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['daveRainbowin'/384154, l='MpServer', x=-519.37, y=90.00, z=506.82]]
	Chunk stats: Client Chunk Cache: 729, 545
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (685,69,850), Chunk: (at 13,4,2 in 42,53; contains blocks 672,0,848 to 687,255,863), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
	Level time: 1375430 game time, 1000 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:410)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1750)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$419/619621481.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 617884528 bytes (589 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.106.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.106.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.106.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.106.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.106.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.106
	FML Language Providers: 
		javafml@28.1
		minecraft@1
		kotori_scala@2.13.1
	Mod List: 
		CyclopsCore-1.14.4-1.6.1.jar Cyclops Core {cyclopscore@1.6.1 DONE}
		blockdrops-1.14.4-1.0.2.jar Block Drops {blockdrops@1.0.2 DONE}
		techemistry-1.14.4-16.jar Techemistry {techemistry@1.14.4-16 DONE}
		ProjectE-1.14.4-PE1.0.0B.jar ProjectE {projecte@1.14.4-PE1.0.0B DONE}
		SilentMechanisms-1.14.4-0.6.9+42.jar Silent's Mechanisms {silents_mechanisms@0.6.9+42 DONE}
		MCFurnace-1.14.4-DEV-1.3.2.jar MCFurnace {mcfurnace@1.3.0 DONE}
		rsgauges-1.14.4-1.1.10-b2.jar Redstone Gauges and Switches {rsgauges@1.1.10-b2 DONE}
		essentials-1.14.4-2.6.4.jar Essentials {essentials@1.14.4-2.6.4 DONE}
		ForgeEndertech-1.14.4-5.1.0.0-build.0066.jar Forge Endertech {forgeendertech@5.1.0.0 DONE}
		xnet-1.14-1.8.7-alpha (1).jar XNet {xnet@1.14-1.8.7-alpha DONE}
		Placebo-1.14.4-2.2.0.jar Placebo {placebo@2.2.0 DONE}
		dankstorage-1.15.jar Dank Storage {dankstorage@1.15 DONE}
		Powah-1.14.4-0.1.3.jar Powah {powah@0.1.3 DONE}
		lowtechcrafting-1.14.4-0.2.1.jar Low Tech Crafting {lowtechcrafting@0.2.1 DONE}
		ObsidianToolsAndArmor-1.14.4-2.0.jar Obsidian Tools and Armor {obsidiantools@2.0 DONE}
		ironshulkerboxes-1.14.4-3.1.12.jar Iron Shulker Boxes {ironshulkerbox@1.14.4-3.1.12 DONE}
		Hwyla-forge-1.10.6-B67_1.14.4.jar Waila {waila@version DONE}
		WaterStrainer-1.14.4-7.0.2.jar Water Strainer {waterstrainer@1.14.4-7.0.2 DONE}
		speedyhoppers-1.14.4-7.jar Speedy Hoppers {speedyhoppers@1.14.4-7 DONE}
		JustEnoughResources-1.14.4-0.10.0.66.jar Just Enough Resources {jeresources@0.10.0.66 DONE}
		refinedstorage-1.7.1.jar Refined Storage {refinedstorage@1.7.1 DONE}
		AirHop-v1.1.1-1.14.4.jar Air Hop {airhop@1.1.1 DONE}
		industrial-foregoing-1.14.4-2.1.2-582ea8b.jar Industrial Foregoing {industrialforegoing@2.1.2 DONE}
		TimeTravelMod-1.14.4-0.1.8.0.jar Time Travel Mod {timetravelmod@1.14.4-0.1.8.0 DONE}
		BetterCrates-1.14.4-1.0.1.jar Better Crates {bettercrates@1.0.1 DONE}
		Lollipop-1.14.4-0.0.18.jar Lollipop {lollipop@0.0.18 DONE}
		ironfurnaces-1.14.4-1.7.0.jar Iron Furnaces {ironfurnaces@1.7.0 DONE}
		practicaltools-1.14.4-1.4.jar Practical Tools {practicaltools@1.14.4-1.4 DONE}
		SilentGear-1.14.4-1.4.5+71.jar Silent Gear {silentgear@1.4.5+71 DONE}
		Masonry-0.3.1.jar Masonry {masonry@1.0 DONE}
		ferroustry-1.3b.jar Ferroustry {ferroustry@1.3b DONE}
		ToolUpgrades-1.14-(v.3.0.0).jar ToolUpgrades {toolupgrades@3.0.0 DONE}
		SolarFluxReborn-1.14.4-14.1.4.jar Solar Flux Reborn {solarflux@14.1.4 DONE}
		portality-1.14.4-2.0.4-b0b3467.jar Portality {portality@2.0.4 DONE}
		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 DONE}
		Fertilization_1.14.4-3.0.6.jar Fertilization {fertilization@3.0.6 DONE}
		Ore+Canes+Mod+1.14.4+(v.1.0.0).jar Ore Canes {ore_canes@1.0.0 DONE}
		PowderPower-1.14.4-3.0.40.jar Powder Power {powder_power@3.0.40 DONE}
		YAMDA-4.0.1.jar YAMDA {yamda@4.0.1 DONE}
		FunOres-1.14.3-2.4.1+15.jar Fun Ores {funores@2.4.1+15 DONE}
		branders-sulfur-potassium-2.2.2-1.14.4.jar Sulfur And Potassium - make gunpowder {sulfurpotassiummod@2.2.2 DONE}
		MoreThanAPickaxe-1.14.4-0.1.1.jar More Than A Pickaxe {morethanapickaxe@0.1.1 DONE}
		SurvivalPlus-1.14.4-0.1.1.jar SurvivalPlus {survivalplus@0.1.1 DONE}
		BiomesOPlenty-1.14.4-9.0.0.261-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.259 DONE}
		CobbleForDays-1.0.2.jar Cobble For Days {cobblefordays@NONE DONE}
		compact-2.6a.jar Compressed {compressed@2.6a DONE}
		Cyclic-1.14.4-0.0.12.jar Cyclic {cyclic@1.14.4-0.0.12 DONE}
		StructuredCrafting-1.14.4-0.2.2.jar StructuredCrafting {structuredcrafting@0.2.2 DONE}
		resynth-3.1.2.jar Resynth {resynth@3.1.2 DONE}
		ultra_amplified_mod-1.14.4-6.12.2.jar Ultra Amplified Mod {ultra_amplified_mod@1.14.4-6.12.2 DONE}
		jei-1.14.4-6.0.0.26.jar Just Enough Items {jei@6.0.0.26 DONE}
		metalbarrels-1.4.jar Metal Barrels {metalbarrels@1.4 DONE}
		OresAboveDiamonds-1.14.4+v1.3Beta.jar Ores Above Diamonds {oresabovediamonds@1.3b DONE}
		icycoal_1.1.jar Icy Coal {icy@1.1 DONE}
		comforts-FORGE-1.14.4-2.0-beta4.jar Comforts {comforts@FORGE-1.14.4-2.0-beta4 DONE}
		SereneSeasons-1.14.4-2.0.0.14-universal.jar Serene Seasons {sereneseasons@1.14.4-2.0.0.14 DONE}
		gardentools-1.14.4-1.0.0.jar Garden Tools {gardentools@1.14.4-1.0.0 DONE}
		alib-1.14.4-8.jar A Lib {alib@1.14.4-8 DONE}
		mcjtylib-1.14-3.5.17-alpha.jar McJtyLib {mcjtylib@1.14-3.5.17-alpha DONE}
		rftoolsbase-1.14-0.0.12-alpha.jar RFToolsBase {rftoolsbase@1.14-0.0.12-alpha DONE}
		rftoolsstorage-1.14-0.0.7-alpha.jar RFToolsStorage {rftoolsstorage@1.14-0.0.7-alpha DONE}
		Spicy_Coal_2.2_quickpatch.jar Spicy Coal {spicy@2.1 DONE}
		ClickMachine-1.14.4-2.1.2.jar Click Machine {clickmachine@2.1.2 DONE}
		rftoolspower-1.14-1.2.12-alpha.jar RFToolsPower {rftoolspower@1.14-1.2.12-alpha DONE}
		GemsPlusPlus-Forge-1.14.4-1.4.0.jar GemsPlusPlus {gemsplusplus@V1.4.0 DONE}
		forge-1.14.4-28.1.106-universal.jar Forge {forge@28.1.106 DONE}
		ColossalChests-1.14.4-1.7.6.jar ColossalChests {colossalchests@1.7.6 DONE}
		ironchest-1.14.4-9.1.5.jar Iron Chests {ironchest@1.14.3-9.0.3 DONE}
		compressed_items-1.14.4-1.2.jar Compressed Items {compressed_items@1.14.4-1.2 DONE}
		alchemistry-1.14.4-8.jar Alchemistry {alchemistry@1.14.4-8 DONE}
		forge-1.14.4-28.1.106-client.jar Minecraft {minecraft@1.14.4 DONE}
		rftoolsutility-1.14-1.2.13-alpha.jar RFToolsUtility {rftoolsutility@1.14-1.2.13-alpha DONE}
		hoppersplus-1.1-1.14.4.jar Hoppers Plus {hoppersplus@1.0 DONE}
		titanium-1.14.4-2.2.9.jar Titanium {titanium@2.2.9 DONE}
		compactores-1.14.4-1.1.2.jar Compact Ores {compactores@1.1.2 DONE}
		SilentLib-1.14.4-4.4.0+44.jar Silent Lib {silentlib@4.4.0+44 DONE}
		Durability101-1.14-0.0.3.jar Durability101 {durability101@0.0.3 DONE}
		Simply+Platinum+-+MC+1.14.4+(1.8).jar Simply Platinum {simplyplatinum@1.8 DONE}
		gates-1.4.0.jar Gates {gates@1.4.0 DONE}
		villagesp_1.14-1.0.jar Village Spawn Point {villagesp@1.0 DONE}
		LargeFluidTank-14.9.0.jar FluidTank {fluidtank@14.9.0 DONE}
		spiketraps-1.1.jar Spike Traps {spiketraps@1.1 DONE}
		rftoolsbuilder-1.14-1.2.12-alpha.jar RFToolsBuilder {rftoolsbuilder@1.14-1.2.12-alpha DONE}
		dimdungeons-1.02-forge-1.14.4.jar Dimensional Dungeons {dimdungeons@1.14.4-1.02 DONE}
		foamdome-3.0.0.jar Foam Dome {foamdome@3.0.0 DONE}
		Quark-r2.0-208.jar Quark {quark@r2.0-208 DONE}
		chemlib-1.14.4-15.jar Chem Lib {chemlib@1.14.4-15 DONE}
		StorageDrawers-1.14.4-6.0.5.jar Storage Drawers {storagedrawers@1.14.4-6.0.3 DONE}
		polyores-1.2.jar Poly's Ores {polyores@1.2 DONE}
		tubesreloaded-1.14.4-1.1.1c.jar Tubes Reloaded {tubesreloaded@1.14.4-1.1.1c DONE}
		RefinedRelocation_1.14.4-6.2.4.jar Refined Relocation {refinedrelocation@6.2.4 DONE}
		modular-routers-1.14.4-5.1.2-7.jar Modular Routers {modularrouters@1.14.4-5.1.2-7 DONE}
		SilentGems-1.14.4-3.4.7+80.jar Silent's Gems 3 {silentgems@3.4.7+80 DONE}
		XL-Food-Mod-1.14.4-2.1.1.jar XL Food Mod {xlfoodmod@2.1.1 DONE}
		forgemod_VoxelMap-1.9.13b_for_1.14.4.jar VoxelMap {voxelmap@1.9.13 DONE}
		ElementaryOres-1.14.4-0.0.1.jar Elementary Ores {elementaryores@1.14.4-0.0.1 DONE}
		Solar-Generation-Mod-1.14.4.jar Solar Generation {solargeneration@1.2.1 DONE}
		ConfigurableTNT-1.14.4-1.0.0.jar Configurable TNT {configurabletnt@1.14.4-1.0.0 DONE}
		chesthopper-2.1.1.jar ChestHopper {chesthopper@v2.1.1 DONE}
	Launched Version: 1.14.4-forge-28.1.106
	LWJGL: 3.2.2 build 10
	OpenGL: Intel(R) UHD Graphics 620 GL version 4.5.0 - Build 25.20.100.6471, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz

**Comment by Buuz135** [comment]
Should be fixed with a titanium update
