### ISSUE TITLE
When I place down a low efficiency generator the game crashed

### ISSUE THREAD

**Issue by PorroxD** [Buuz135/Portality#71]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 18/01/20 09:56 AM
Description: Ticking block entity

java.lang.AbstractMethodError: Method com/buuz135/portality/tile/LowEfficiencyGeneratorTile.getWorld()Lnet/minecraft/world/World; is abstract
	at com.buuz135.portality.tile.LowEfficiencyGeneratorTile.getWorld(LowEfficiencyGeneratorTile.java) ~[?:2.1.1] {re:classloading}
	at com.hrznstudio.titanium.component.progress.ProgressBarComponent.tickBar(ProgressBarComponent.java:166) ~[?:2.3.2] {re:classloading}
	at com.hrznstudio.titanium.component.progress.MultiProgressBarHandler.update(MultiProgressBarHandler.java:39) ~[?:2.3.2] {re:classloading}
	at com.hrznstudio.titanium.block.tile.ActiveTile.func_73660_a(ActiveTile.java:185) ~[?:2.3.2] {re:classloading}
	at com.hrznstudio.titanium.block.tile.GeneratorTile.func_73660_a(GeneratorTile.java:100) ~[?:2.3.2] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:473) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:368) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:841) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:776) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:634) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.buuz135.portality.tile.LowEfficiencyGeneratorTile.getWorld(LowEfficiencyGeneratorTile.java)
	at com.hrznstudio.titanium.component.progress.ProgressBarComponent.tickBar(ProgressBarComponent.java:166)
	at com.hrznstudio.titanium.component.progress.MultiProgressBarHandler.update(MultiProgressBarHandler.java:39)
	at com.hrznstudio.titanium.block.tile.ActiveTile.func_73660_a(ActiveTile.java:185)
	at com.hrznstudio.titanium.block.tile.GeneratorTile.func_73660_a(GeneratorTile.java:100)

-- Block entity being ticked --
Details:
	Name: portality:generator // com.buuz135.portality.tile.LowEfficiencyGeneratorTile
	Block: Block{portality:generator}[subfacing=north]
	Block location: World: (-134,68,57), Chunk: (at 10,4,9 in -9,3; contains blocks -144,0,48 to -129,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Block: Block{portality:generator}[subfacing=north]
	Block location: World: (-134,68,57), Chunk: (at 10,4,9 in -9,3; contains blocks -144,0,48 to -129,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:473)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:368)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Porro'/196, l='Mundo nuevo', x=-133.25, y=68.00, z=55.93]]
	Chunk stats: ServerChunkCache: 2136
	Level dimension: DimensionType{minecraft:overworld}
	Level name: Mundo nuevo
	Level seed: 7170262156601569649
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (48,70,48), Chunk: (at 0,4,0 in 3,3; contains blocks 48,0,48 to 63,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 101436 game time, 10064 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 5622 (now: false), thunder time: 19907 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:776)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:634)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.15.1
	Minecraft Version ID: 1.15.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2136997872 bytes (2037 MB) / 3221225472 bytes (3072 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 2
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx3072m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.1-30.0.20.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.1-30.0.20.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.0-milestone.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.1-30.0.20.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.1-30.0.20.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.1-30.0.20.jar fml TRANSFORMATIONSERVICE 
	FML: 30.0
	Forge: net.minecraftforge:30.0.20
	FML Language Providers: 
		javafml@30.0
		minecraft@1
	Mod List: 
		forge-1.15.1-30.0.20-client.jar Minecraft {minecraft@1.15.1 DONE}
		colorfularmor-1.15.1-1.1.jar.jar Colorful Armor {colorfularmor@1.1 DONE}
		forge-1.15.1-30.0.20-universal.jar Forge {forge@30.0.20 DONE}
		titanium-1.15.1-2.3.2.jar Titanium {titanium@2.3.2 DONE}
		portality-1.15.1-2.1.1-602aec8.jar Portality {portality@2.1.1 DONE}
		music_player-1.15.1-2.0.7.51.jar Music Player {musicplayer@2.0.7.51 DONE}
		ultra_amplified_dimension-1.15.1-7.0.4.jar Ultra Amplified Dimension {ultra_amplified_dimension@1.15.1-7.0.4 DONE}
		u_team_core-1.15.1-2.9.3.145.jar U Team Core {uteamcore@2.9.3.145 DONE}
		duckymod-1.15.1-0.5.0.jar Ducky Mod {duckymod@1.15.1-0.5.0 DONE}
		Hwyla-forge-1.10.7-B71_1.15.1.jar Waila {waila@version DONE}
		jei-1.15.1-6.0.0.1.jar Just Enough Items {jei@6.0.0.1 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['Porro'/196, l='Mundo nuevo', x=-133.25, y=68.00, z=55.93]]
	Data Packs: vanilla, mod:forge (incompatible), mod:jei (incompatible), mod:waila (incompatible), mod:ultra_amplified_dimension (incompatible), mod:duckymod (incompatible), mod:musicplayer (incompatible), mod:uteamcore, mod:colorfularmor (incompatible), mod:portality (incompatible), mod:titanium (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Versions**
- portality-1.15.1-2.1.1-602aec8
- titanium-1.15.1-2.3.2
- 1.15.1-forge-30.0.20

**I have other mods:**
colorfularmor-1.15.1-1.1
duckymod-1.15.1-0.5.0
Hwyla-forge-1.10.7-B71_1.15.1
jei-1.15.1-6.0.0.1
music_player-1.15.1-2.0.7.51
u_team_core-1.15.1-2.9.3.145
ultra_amplified_dimension-1.15.1-7.0.4

**Comment by Buuz135** [comment]
Try updating forge

**Comment by PorroxD** [comment]
ok, I will do it, thanks!
