### ISSUE TITLE
[1.15.2] crash on breaking portal controller

### ISSUE THREAD

**Issue by thvless** [Buuz135/Portality#83]
The game crashes when breaking a portal controller when it's in a valid portal structure i.e. if i just place a portal controller and break it nothing however if i make a portal then break the controller the game crashes:
`---- Minecraft Crash Report ----
// Don't do that.

Time: 9/6/20 11:03 PM
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property DirectionProperty{name=subfacing, clazz=class net.minecraft.util.Direction, values=[north, south, west, east]} as it does not exist in Block{minecraft:air}
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:93) ~[?:?] {re:mixin,re:classloading}
	at com.buuz135.portality.proxy.client.render.TESRPortal.render(TESRPortal.java:209) ~[?:2.1.2] {re:classloading}
	at com.buuz135.portality.proxy.client.render.TESRPortal.func_225616_a_(TESRPortal.java:44) ~[?:2.1.2] {re:classloading}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228855_a_(TileEntityRendererDispatcher.java:125) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.lambda$renderTileEntity$0(TileEntityRendererDispatcher.java:100) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher$$Lambda$17509/1435907852.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228853_a_(TileEntityRendererDispatcher.java:184) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228850_a_(TileEntityRendererDispatcher.java:98) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:436) ~[?:?] {re:classloading}
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4252) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:926) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:686) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:924) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:codechickenlib:IItemRenderer,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:codechickenlib:IItemRenderer,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.35.jar:31.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$487/1391240208.call(Unknown Source) [forge-1.15.2-31.2.35.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.2.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.2.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:93)
	at com.buuz135.portality.proxy.client.render.TESRPortal.render(TESRPortal.java:209)
	at com.buuz135.portality.proxy.client.render.TESRPortal.func_225616_a_(TESRPortal.java:44)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228855_a_(TileEntityRendererDispatcher.java:125)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.lambda$renderTileEntity$0(TileEntityRendererDispatcher.java:100)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher$$Lambda$17509/1435907852.run(Unknown Source)

-- Block Entity Details --
Details:
	Name: portality:controller // com.buuz135.portality.tile.ControllerTile
	Block: Block{portality:controller}[subfacing=north]
	Block location: World: (-3,68,-12), Chunk: (at 13,4,4 in -1,-1; contains blocks -16,0,-16 to -1,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Block: Block{minecraft:air}
	Block location: World: (-3,68,-12), Chunk: (at 13,4,4 in -1,-1; contains blocks -16,0,-16 to -1,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228853_a_(TileEntityRendererDispatcher.java:184)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228850_a_(TileEntityRendererDispatcher.java:98)
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:436)
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4252)
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:926)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Altrath'/167, l='MpServer', x=-2.00, y=68.00, z=-14.98]]
	Chunk stats: Client Chunk Cache: 441, 289
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: -2808970398538440228
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (0,89,0), Chunk: (at 0,5,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 346329 game time, 6000 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:611)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1763)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:567)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$487/1391240208.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2175842216 bytes (2075 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.35.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.35.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.35.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.35.jar runtimedistcleaner PLUGINSERVICE 
		/%5Bclient%5Dpreview_OptiFine_1.15.2_HD_U_G1_pre30.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.35.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.35
	FML Language Providers: 
		javafml@31.2
		minecraft@1
		kotlinfml@1.5.2
		kotori_scala@2.13.2-build-2
	Mod List: 
		CyclopsCore-1.15.2-1.8.3.jar Cyclops Core {cyclopscore@1.8.3 DONE}
		WizardsAnimalsPlus2.2.jar Wizard Animals Plus {wizard_animals_plus@1.0.0 DONE}
		AdditionalEnchantedMiner-1.15.2-15.3.3.jar QuarryPlus {quarryplus@15.3.3 DONE}
		NetherPortalFix_1.15.2-6.0.2.jar NetherPortalFix {netherportalfix@6.0.2 DONE}
		zombiehs_1.15-2.4.jar Zombie Horse Spawn {zombiehs@2.4 DONE}
		endportalrecipe_1.15-2.1.jar End Portal Recipe {endportalrecipe@2.1 DONE}
		Wyrmroost-1.1.2.jar Wyrmroost {wyrmroost@1.1.1-DEV DONE}
		ElenaiDodge-1.15.2-1.7.2.jar Elenai Dodge {elenaidodge@1.15.2-1.7.2 DONE}
		clayconversion-1.15-1.0.jar Clay Conversion {clayconversion@1.0 DONE}
		areas_1.15-1.0(1).jar Areas {areas@1.0 DONE}
		powershot-1.1.0-1.15.2-forge.jar Powershot {powershot@1.1.0-1.15.2-forge DONE}
		EditSign-1.15.2-2.0.0+7.jar Edit Sign {edit_sign@2.0.0+7 DONE}
		teamsmod-1.15.2-R2-hotfix-2.jar Teams {teamsmod@1.15.2-R2-hotfix DONE}
		mcws-win-1.15.2-v1.0.2.jar Macaw's Windows {mcwwindows@1.0.2 DONE}
		strawgolem-1.15.2-1.7.1.jar Straw Golem {strawgolem@1.15.2-1.7.1 DONE}
		Guide-API-VP-1.15.2-2.2.0.jar Guide-API VP {guideapi-vp@2.2.0 DONE}
		BetterCaves-1.15.2-1.0.jar YUNG's Better Caves {bettercaves@1.15.2-1.0 DONE}
		ForgeEndertech-1.15.2-6.0.4.0-build.0044.jar Forge Endertech {forgeendertech@6.0.4.0 DONE}
		TerraForged-1.15.2-0.1.2.jar TerraForged {terraforged@0.1.2 DONE}
		softerhayb_1.15-1.1.jar Softer Hay Bales {softerhayb@1.1 DONE}
		XaerosWorldMap_1.10.1_Forge_1.15.2(1).jar Xaero's World Map {xaeroworldmap@1.10.1 DONE}
		Controlling-6.1.4.jar Controlling {controlling@6.1.4 DONE}
		[client]ReAuth-1.14-1.15-3.8.1.jar ReAuth {reauth@3.8.1 DONE}
		setworldsp_1.15-1.3.jar Set World Spawn Point {setworldsp@1.3 DONE}
		Bookshelf-1.15.2-5.5.33.jar Bookshelf {bookshelf@5.5.33 DONE}
		[client]itemzoom-1.15.2-2.1.0.jar Item Zoom {itemzoom@2.1.0 DONE}
		randompatches-1.15.2-1.21.1.2.jar RandomPatches {randompatches@1.15.2-1.21.1.2 DONE}
		ChanceCubes-1.15.2-5.0.2.377.jar Chance Cubes {chancecubes@1.15.2-5.0.2.377 DONE}
		cryingghasts_1.15-1.1.jar Crying Ghasts {cryingghasts@1.1 DONE}
		ironshulkerboxes-1.15.2-4.0.1.jar Iron Shulker Boxes {ironshulkerbox@1.15.2-4.0.1 DONE}
		Morpheus-1.15.2-4.2.50.jar Morpheus {morpheus@version DONE}
		venture-1.0.0-1.15.2.jar Venture {venture@1.0.0 DONE}
		VTweaks-1.15.2-3.1.6.jar V-Tweaks {vtweaks@3.1.5 DONE}
		DragonMountsLegacy-1.0.5.jar Dragon Mounts Legacy {dragonmounts@1.0.5 DONE}
		structure-gel-api-1.15.2-1.1.0.jar Structure Gel API {structure_gel@1.1.0 DONE}
		corpse-1.15.2-1.0.2.jar Corpse {corpse@1.15.2-1.0.2 DONE}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		dwmh-1.15.2-4.0.0.jar Dude! Where's my Horse? {dwmh@NONE DONE}
		torchmaster-2.2.2.jar Torchmaster {torchmaster@2.2.2 DONE}
		[client]AmbientSounds_v3.0.20_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		Ping-1.15.2-1.6.4.jar Ping {ping@1.15.2-1.6.4 DONE}
		BiomesOPlenty-1.15.2-10.0.0.366-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.366 DONE}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		[client]Blur-1.1.0-1.jar Blur {blur@1.1.0-1 DONE}
		WorldProtector+1.15.2.jar WorldProtector {worldprotector@1.0 DONE}
		valkyrielib-1.15.2-3.0.2.1.jar ValkyrieLib {valkyrielib@1.15.2-3.0.2.1 DONE}
		simplechunkloaders-1.15.2-1.0.2.0.jar Simple Chunk Loaders {simplechunkloaders@NONE DONE}
		valhelsia_structures-15.0.3a.jar Valhelsia Structures {valhelsia_structures@15.0.3a DONE}
		Lollipop-1.15.2-1.0.15.jar Lollipop {lollipop@1.0.15 DONE}
		dungeons-plus-1.15.2-1.0.2.jar Dungeons Plus {dungeons_plus@1.0.2 DONE}
		MinecraftCapes+Forge+1.15.2-v10.jar MinecraftCapes Mod {minecraftcapes@v10 DONE}
		rare-ice-0.1.6.jar Rare Ice {rare-ice@0.1.6 DONE}
		masonry-1.15.2-0.3.4.jar Masonry {masonry@NONE DONE}
		portality-1.15.2-2.1.2-aaa257f.jar Portality {portality@2.1.2 DONE}
		Trapcraft-1.15.2-2.7.1.jar Trapcraft {trapcraft@2.7.1 DONE}
		curios-FORGE-1.15.2-2.0.2.4.jar Curios API {curios@FORGE-1.15.2-2.0.2.4 DONE}
		Botania-r1.15-388.jar Botania {botania@r1.15-388 DONE}
		tetra-1.15.2-2.18.1.jar Tetra {tetra@1.15.2-2.18.1 DONE}
		Patchouli-1.15.2-1.2-35.jar Patchouli {patchouli@1.15.2-1.2-35 DONE}
		flying_things-1.8.9-1.15.2.jar The Flying Things {flying_things@1.8.9 DONE}
		collective-1.15.2-1.39.jar Collective {collective@1.39 DONE}
		config-2-3.0.jar Cloth Config v2 API {cloth-config2@3.0 DONE}
		Enemyz-1.15.2-1.0.1.jar Enemyz {enemyz@1.0.1 DONE}
		worldedit-forge-mc1.15.2-7.1.0.jar WorldEdit {worldedit@7.1.0;48cc31c DONE}
		noRecipeBook_v1.5.2formc1.15.2.jar No Recipe Book {norecipebook@1.5.2 DONE}
		curiouselytra-FORGE-1.15.2-2.0.jar Curious Elytra {curiouselytra@FORGE-1.15.2-2.0 DONE}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		Emojicord-1.15.2-1.1.1.39-universal.jar Emojicord {emojicord@1.1.1.39 DONE}
		Zmod+1.15.2-1.05.jar ZmodSkills {zmod@1.04 DONE}
		undergarden-0.1.5(1).jar The Undergarden {undergarden@0.1.5 DONE}
		AdChimneys-1.15.2-5.0.7.0-build.0047.jar Advanced Chimneys {adchimneys@5.0.7.0 DONE}
		FastLeafDecay-v22.jar FastLeafDecay {fastleafdecay@v22 DONE}
		CodeChickenLib-1.15.2-3.3.1.379-universal.jar CodeChicken Lib {codechickenlib@3.3.1.379 DONE}
		ServerTabInfo-1.15.2-1.2.6.jar Server Tab Info {servertabinfo@1.2.6 DONE}
		BetterMineshaftsForge-1.15.2-1.3.jar YUNG's Better Mineshafts {bettermineshafts@1.15.2-1.3 DONE}
		BetterAdvancements-1.15.2-0.1.0.96.jar Better Advancements {betteradvancements@0.1.0.96 DONE}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 DONE}
		skin_changer-0.1-beta.2.jar Skin Changer {skin_changer@0.1-beta.2 DONE}
		torchslabmod-1.15.2_v1.7.0.jar Torch Slab Mod {torchslabmod@1.7.0 DONE}
		EquipmentTooltips-1.15.2-1.4.0+11.jar Equipment Tooltips {equipmenttooltips@1.4.0+11 DONE}
		damage_indicator-0.1.0.jar Ama's Damage Indicator {damage_indicator@0.0.9 DONE}
		equaldragons-1.2.jar Equal Dragons {equaldragons@1.2 DONE}
		mermaidtail-1.4.jar Mermaid Tail Mod {mermaidtail@1.15.2-1.4.0 DONE}
		Bountiful+Baubles-1.15.2-0.0.1.jar Bountiful Baubles {bountifulbaubles@NONE DONE}
		Mine+and+Slash-1.15.2-3.6.14.jar Mine and Slash {mmorpg@3.6.14 DONE}
		jei-1.15.2-6.0.0.4.jar Just Enough Items {jei@6.0.0.4 DONE}
		EverlastingAbilities-1.15.2-1.6.3.jar EverlastingAbilities {everlastingabilities@1.6.3 DONE}
		Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 DONE}
		caelus-FORGE-1.15.2-2.0-beta3.jar Caelus API {caelus@FORGE-1.15.2-2.0-beta3 DONE}
		Upgrade-Aquatic-1.15.2-1.7.1.jar Upgrade Aquatic {upgrade_aquatic@1.7.1 DONE}
		DurabilityNotifier-1.15-1.0.0.jar Durability Notifier {durabilitynotifier@1.0.0 DONE}
		reap-1.12.3.jar Reap Mod {reap@1.12.3 DONE}
		skeletonhs_1.15-1.3.jar Skeleton Horse Spawn {skeletonhs@1.3 DONE}
		create-mc1.15.2_v0.2.4d.jar Create {create@mc1.15.2_v0.2.4d DONE}
		Waystones_1.15.2-6.0.2.jar Waystones {waystones@6.0.2 DONE}
		goldenhopper-1.1.1-1.15.2.jar Golden Hopper {goldenhopper@1.1.1 DONE}
		Clumps-5.0.2.jar Clumps {clumps@5.0.2 DONE}
		RingOfRepair-1.15.2-1.1.33.jar Ring of Repair {ring_of_repair@1.1.30 DONE}
		mgui-1.15.2-2.1.1.jar mgui {mgui@2.1.1 DONE}
		LightOverlay-4.6.1.jar Light Overlay Forge {lightoverlay-forge@4.6.1 DONE}
		appliedenergistics2-7.0.0-beta.2.jar Applied Energistics 2 {appliedenergistics2@7.0.0-beta.2 DONE}
		TravelersBackpack-1.15.2-4.0.6.jar Traveler's Backpack {travelersbackpack@4.0.6 DONE}
		SereneSeasons-1.15.2-3.0.0.73-universal.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.73 DONE}
		BasicNetherOres-1.15.2-4.0.3.jar Basic Nether Ores {bno@4.0.3 DONE}
		DungeonCrawl-1.15.2-2.0.2.jar Dungeon Crawl {dungeoncrawl@2.0.2 DONE}
		Coins-1.15.2-1.0.1.jar Coins {coins@1.0.1 DONE}
		snowundertrees-1.15.1-v1.0.jar Snow Under Trees {snowundertrees@v1.0 DONE}
		additional_lights-1.15.2-2.0.2.jar Additional Lights {additional_lights@2.0.2 DONE}
		iChunUtil-1.15.2-8.0.3.jar iChunUtil {ichunutil@8.0.3 DONE}
		fixedanvilrepaircost_1.15-1.1.jar Fixed Anvil Repair Cost {fixedanvilrepaircost@1.1 DONE}
		forge-1.15.2-31.2.35-universal.jar Forge {forge@31.2.35 DONE}
		Atum-1.15.2-2.1.4.jar Atum 2 {atum@1.15.2-2.1.4 DONE}
		Bountiful-1.15.2-3.1.2.jar Bountiful {bountiful@1.15.2-3.1.2 DONE}
		deathbackup-1.15.2-2.0.0.jar Bigger Rabbit Hitboxes {deathbackup@NONE DONE}
		ColossalChests-1.15.2-1.7.12.jar ColossalChests {colossalchests@1.7.12 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		CraftingTweaks_1.15.1-11.0.0.jar Crafting Tweaks {craftingtweaks@11.0.0 DONE}
		forge-1.15.2-31.2.35-client.jar Minecraft {minecraft@1.15.2 DONE}
		EnchantmentDescriptions-1.15.2-2.0.8.jar EnchantmentDescriptions {enchdesc@2.0.8 DONE}
		theoneprobe-1.15-2.0.7.jar The One Probe {theoneprobe@1.15-2.0.7 DONE}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		titanium-1.15.2-2.4.2.jar Titanium {titanium@2.4.2 DONE}
		Ma-Chat-1.15.2-3.1.0.jar Ma Chat {ma-chat@1.15.2-3.1.0 DONE}
		ImmersiveEngineering-0.15-108.jar Immersive Engineering {immersiveengineering@0.15-108 DONE}
		inventorytotem_1.15-1.1.jar Inventory Totem {inventorytotem@1.1 DONE}
		baubles-1.7.1-1.15.2.jar Baubles {baubles@1.7.1 DONE}
		wards-1.15.2-1.4.0(1).jar Wards {wards@1.15.2-1.4.0 DONE}
		MiscAdditions-1.2.3.jar Misc Additions {miscadditions@1.2.3 DONE}
		dimdungeons-1.07-forge-1.15.2.jar Dimensional Dungeons {dimdungeons@1.15.2-1.07 DONE}
		justplayerheads_1.15.2-1.4.jar Just Player Heads {justplayerheads@1.4 DONE}
		Savage-and-Ravage-1.15.2-1.1.4.jar Savage & Ravage {savageandravage@1.1.4 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		AkashicTome-1.3-13.jar Akashic Tome {akashictome@1.3-13 DONE}
		Quark-r2.1-245.jar Quark {quark@r2.1-245 DONE}
		[1.15.2]+SecurityCraft+v1.8.19.1(1).jar SecurityCraft {securitycraft@v1.8.19.1 DONE}
		sit-1.15.1-v1.3.jar Sit {sit@v1.3 DONE}
		performant-1.15-3.10m(1).jar Performant {performant@3.10m DONE}
		OfflineSkins-1.15.2-v2.jar OfflineSkins {offlineskins@1.15.2-v2 DONE}
		grindr-1.15.2-0.0.1.6.jar Grindr {grindr@1.15.2-0.0.1.6 DONE}
		discordrpc-2.0.5-1.15.jar DiscordRichPresence {discordrpc@2.0.5 DONE}
		passers-battletowers.jar Passer's Battle Towers {battle-towers@0.9.0 DONE}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		[client]CustomCursorMod-1.2.2.jar Custom Cursor Mod {customcursormod@1.2.2 DONE}
		[client]BackTools-1.15.2-8.0.0.jar Back Tools {backtools@8.0.0 DONE}
		guardscraft-1.15.2-1.0.2.jar GuardsCraft {guardscraft@1.0.2--1.15.2 DONE}
		BetterPvP_20.20.1_Forge_1.15.2.jar Better PVP Mod {xaerobetterpvp@20.20.1 DONE}
		CosmeticArmorReworked-1.15.2-v3a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.15.2-v3a DONE}
		[client]SoundFilters-0.14_for_1.15.2.jar Sound Filters {soundfilters@0.14_for_1.15.2 DONE}
		Stairway_1.15.2_v15.jar StairwayToAether {stairway@v15 DONE}
		EnderMail-1.15.2-1.1.3.jar Ender Mail {endermail@1.15.2-1.1.3 DONE}
	Patchouli open book context: n/a
	Launched Version: 1.15.2-forge-31.2.35
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Quadro P1000/PCIe/SSE2 GL version 4.6.0 NVIDIA 443.18, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, mod_resources, file/Cuck Labyrinth Resources.zip
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre30
	OptiFine Build: 20200622-083032
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v7.2.zip
	OpenGlVersion: 4.6.0 NVIDIA 443.18
	OpenGlRenderer: Quadro P1000/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12`

**Comment by thvless** [comment]
Update: disabling optifine specifically OptiFine 1.15.2 HD U G1 pre30 fixes the crashing
