### ISSUE TITLE
[1.16.1] Crash when interacting with Portal Controller

### ISSUE THREAD

**Issue by DSlyDog** [Buuz135/Portality#84]
Using the 1.16.1 version, when I try to interact with the Portal Controller block, the game crashes, giving a ClassCastException. This happens when I click the block to open the GUI:

`java.lang.ClassCastException: net.minecraft.util.text.TranslationTextComponent cannot be cast to net.minecraft.util.IReorderingProcessor
	at net.minecraft.client.gui.screen.Screen.renderToolTip(Screen.java:142) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.func_238654_b_(Screen.java:135) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.hrznstudio.titanium.client.screen.ScreenAddonScreen.renderForeground(ScreenAddonScreen.java:84) ~[?:3.0.4] {re:classloading}
	at com.buuz135.portality.gui.ControllerScreen.renderForeground(ControllerScreen.java:75) ~[?:3.1.0] {re:classloading}
	at com.hrznstudio.titanium.client.screen.ScreenAddonScreen.func_230430_a_(ScreenAddonScreen.java:65) ~[?:3.0.4] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:327) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:491) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.2-33.0.42.jar:33.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$422/987595204.call(Unknown Source) [forge-1.16.2-33.0.42.jar:33.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}`

**Comment by Buuz135** [comment]
You are using a 1.16.1 mod with a 1.16.2 forge
