### ISSUE TITLE
[1.16.1] Crash when breaking the Portal Controller block

### ISSUE THREAD

**Issue by DSlyDog** [Buuz135/Portality#85]
When I try to break the Portal Controller block, the game crashes. There is this error in the log:
`java.lang.NoSuchMethodError: net.minecraft.world.IWorld.func_201672_e()Lnet/minecraft/world/World;
	at com.buuz135.portality.block.ControllerBlock.func_176206_d(ControllerBlock.java:75) ~[?:3.1.0]
	at net.minecraft.server.management.PlayerInteractionManager.removeBlock(PlayerInteractionManager.java:273) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:245) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_229860_a_(PlayerInteractionManager.java:220) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:149) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandler.java:860) ~[?:?]
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40) ~[?:?]
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:34) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$6888/66118459.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:172) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:729) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:156) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:134) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:712) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:706) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:150) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:692) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) [?:?]
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$6101/753405061.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[07Sep2020 17:41:31.987] [Render thread/FATAL] [net.minecraft.client.Minecraft/]: Unreported exception thrown!
java.lang.NoSuchMethodError: net.minecraft.world.IWorld.func_201672_e()Lnet/minecraft/world/World;
	at com.buuz135.portality.block.ControllerBlock.func_176206_d(ControllerBlock.java:75) ~[?:3.1.0]
	at net.minecraft.client.multiplayer.PlayerController.func_187103_a(PlayerController.java:114) ~[?:?]
	at net.minecraft.client.multiplayer.PlayerController.func_180511_b(PlayerController.java:134) ~[?:?]
	at net.optifine.override.PlayerControllerOF.func_180511_b(PlayerControllerOF.java:50) ~[?:?]
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1288) ~[?:?]
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1591) ~[?:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1437) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:930) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.2-33.0.42.jar:33.0]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$424/209360767.call(Unknown Source) [forge-1.16.2-33.0.42.jar:33.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?]`

**Comment by Buuz135** [comment]
You are using a 1.16.1 mod with a 1.16.2 forge
