### ISSUE TITLE
[1.16.3] Crashing when attempting to travel through a portal

### ISSUE THREAD

**Issue by AnonymousDonald** [Buuz135/Portality#95]
I've tried this both on a forge server and locally, both times it will crash.
Orginally the server would crash every time I joined back in, was able to fix it by deleting my player data, turning off the portal and picking up my stuff from the gravestone.

The following is the crashlog of my local game:

```
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 10/15/20, 8:19 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraft.entity.player.ServerPlayerEntity.lambda$changeDimension$6(ServerPlayerEntity.java:655) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at com.hrznstudio.titanium.util.TeleportationUtils$1.placeEntity(TeleportationUtils.java:44) ~[?:3.1.0] {re:classloading}
	at net.minecraft.entity.player.ServerPlayerEntity.changeDimension(ServerPlayerEntity.java:643) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at com.hrznstudio.titanium.util.TeleportationUtils.teleportEntity(TeleportationUtils.java:41) ~[?:3.1.0] {re:classloading}
	at com.buuz135.portality.handler.TeleportHandler.tick(TeleportHandler.java:99) ~[?:3.1.1] {re:classloading}
	at com.buuz135.portality.tile.ControllerTile.func_73660_a(ControllerTile.java:157) ~[?:3.1.1] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:366) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:847) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:120) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:638) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:834) [?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.player.ServerPlayerEntity.lambda$changeDimension$6(ServerPlayerEntity.java:655) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at com.hrznstudio.titanium.util.TeleportationUtils$1.placeEntity(TeleportationUtils.java:44) ~[?:3.1.0] {re:classloading}
	at net.minecraft.entity.player.ServerPlayerEntity.changeDimension(ServerPlayerEntity.java:643) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at com.hrznstudio.titanium.util.TeleportationUtils.teleportEntity(TeleportationUtils.java:41) ~[?:3.1.0] {re:classloading}
	at com.buuz135.portality.handler.TeleportHandler.tick(TeleportHandler.java:99) ~[?:3.1.1] {re:classloading}
	at com.buuz135.portality.tile.ControllerTile.func_73660_a(ControllerTile.java:157) ~[?:3.1.1] {re:classloading}
-- Block entity being ticked --
Details:
	Name: portality:controller // com.buuz135.portality.tile.ControllerTile
	Block: Block{portality:controller}[subfacing=south]
	Block location: World: (68,67,263), Chunk: (at 4,4,7 in 4,16; contains blocks 64,0,256 to 79,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Block: Block{portality:controller}[subfacing=south]
	Block location: World: (68,67,263), Chunk: (at 4,4,7 in 4,16; contains blocks 64,0,256 to 79,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:366) ~[?:?] {re:classloading,re:mixin}


-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['AnonymousDonald'/391, l='ServerLevel[New World]', x=68.23, y=68.00, z=262.93]]
	Chunk stats: ServerChunkCache: 9191
	Level dimension: minecraft:overworld
	Level spawn location: World: (32,80,0), Chunk: (at 0,5,0 in 2,0; contains blocks 32,0,0 to 47,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 6528 game time, 6528 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 58319 (now: false), thunder time: 128662 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:847) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:120) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:638) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:834) [?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Linux (amd64) version 5.4.0-7642-generic
	Java Version: 11.0.8, Flathub
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Flathub
	Memory: 1302894720 bytes (1242 MB) / 3892314112 bytes (3712 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 16
	JVM Flags: 8 total; -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 7.0.1+78+master.e9771d8
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.17.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.17.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.3-34.1.17.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.17.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.3_HD_U_G3_MOD.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.17.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.17
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		Cucumber-1.16.3-4.1.2.jar Cucumber Library {cucumber@4.1.2 DONE}
		TrashSlot_1.16.3-12.2.0.jar TrashSlot {trashslot@12.2.0 DONE}
		aiotbotania-1.16.2-1.3.2.jar AIOT Botania {aiotbotania@1.3.2 DONE}
		curiousshulkerboxes-forge-1.16.3-4.0.0.1.jar Curious Shulker Boxes {curiousshulkerboxes@1.16.3-4.0.0.1 DONE}
		jei-1.16.3-7.5.0.42.jar Just Enough Items {jei@7.3.2.29 DONE}
		Uppers-0.3.1.jar Uppers {uppers@0.3.1 DONE}
		Mekanism-1.16.3-10.0.11.436.jar Mekanism {mekanism@10.0.11 DONE}
		mcw-windows-1.0.2-mc1.16.3.jar Macaw's Windows {mcwwindows@1.0.2 DONE}
		SilentMechanisms-1.16.3-0.8.3+67.jar Silent's Mechanisms {silents_mechanisms@0.8.3+67 DONE}
		reap-1.16.3-1.0.2.jar Reap Mod {reap@1.16.3-1.0.2 DONE}
		rsgauges-1.16.3-1.2.4.jar Gauges and Switches {rsgauges@1.2.4 DONE}
		invtweaks-1.16.2-1.0.0.jar Inventory Tweaks Renewed {invtweaks@1.16.2-1.0.0 DONE}
		BetterCaves-1.16.2-1.0.2.jar YUNG's Better Caves {bettercaves@1.16.2-1.0.2 DONE}
		Waystones_1.16.3-7.3.0.jar Waystones {waystones@7.3.0 DONE}
		ForgeEndertech-1.16.3-7.0.4.0-build.0017.jar Forge Endertech {forgeendertech@7.0.4.0 DONE}
		Clumps-6.0.0.11.jar Clumps {clumps@6.0.0.11 DONE}
		XaerosWorldMap_1.11.0_Forge_1.16.3.jar Xaero's World Map {xaeroworldmap@1.11.0 DONE}
		CTM-MC1.16.1-1.1.1.5.jar ConnectedTexturesMod {ctm@MC1.16.1-1.1.1.5 DONE}
		CookingForBlockheads_1.16.3-9.2.1.jar Cooking for Blockheads {cookingforblockheads@9.2.1 DONE}
		Placebo-1.16.3-4.3.1.jar Placebo {placebo@4.3.1 DONE}
		comforts-forge-1.16.3-4.0.0.1.jar Comforts {comforts@1.16.3-4.0.0.1 DONE}
		Powah-1.16.3-2.3.0.jar Powah {powah@2.3.0 DONE}
		curioofundying-forge-1.16.3-5.0.0.1.jar Curio of Undying {curioofundying@1.16.3-5.0.0.1 DONE}
		Bookshelf-1.16.3-8.4.13.jar Bookshelf {bookshelf@8.4.13 DONE}
		BotanyPots-1.16.3-5.0.1.jar BotanyPots {botanypots@5.0.1 DONE}
		Reliquary-1.16.3-1.3.4.1015.jar Reliquary {xreliquary@1.16.3-1.3.4.1015 DONE}
		u_team_core-1.16.3-3.1.9.181.jar U Team Core {uteamcore@3.1.9.181 DONE}
		randompatches-1.16.2-1.22.1.2.jar RandomPatches {randompatches@1.16.2-1.22.1.2 DONE}
		DarkUtilities-1.16.3-6.0.1.jar Dark Utilities {darkutils@6.0.1 DONE}
		Apotheosis-1.16.3-4.3.1.jar Apotheosis {apotheosis@4.3.1 DONE}
		mcw-doors-1.0.1fix-mc1.16.3-1.16.2.jar Macaw's Doors {mcwdoors@1.0.1 DONE}
		Morpheus-1.16.3-4.2.59.jar Morpheus {morpheus@version DONE}
		MekanismGenerators-1.16.3-10.0.11.436.jar Mekanism: Generators {mekanismgenerators@10.0.11 DONE}
		Hwyla-forge-1.10.11-B78_1.16.2.jar Waila {waila@1.10.11-B78_1.16.2 DONE}
		WAWLA-1.16.3-6.0.1.jar WAWLA {wawla@6.0.1 DONE}
		Ma-Essentials-1.16.3-3.4.0.jar Ma Essentials {maessentials@1.16.3-3.4.0 DONE}
		JustEnoughResources-1.16.3-0.12.0.100.jar Just Enough Resources {jeresources@0.12.0.100 DONE}
		forge-1.16.3-34.1.17-universal.jar Forge {forge@34.1.17 DONE}
		MysticalAgradditions-1.16.3-4.1.0.jar Mystical Agradditions {mysticalagradditions@4.1.0 DONE}
		refinedstorage-1.9.7.jar Refined Storage {refinedstorage@1.9.7 DONE}
		MysticalAgriculture-1.16.3-4.1.0.jar Mystical Agriculture {mysticalagriculture@4.1.0 DONE}
		CraftingTweaks_1.16.3-12.2.0.jar Crafting Tweaks {craftingtweaks@12.2.0 DONE}
		forge-1.16.3-34.1.17-client.jar Minecraft {minecraft@1.16.3 DONE}
		mcw-bridges-1.0.4-mc1.16.3.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		industrial-foregoing-1.16.3-3.1.1-a834e76.jar Industrial Foregoing {industrialforegoing@3.1.1 DONE}
		useful_backpacks-1.16.3-1.11.5.82.jar Useful Backpacks {usefulbackpacks@1.11.5.82 DONE}
		resourcefulbees-1.16.3-0.5.1a.jar Resourceful Bees {resourcefulbees@1.16.3-0.5.1a DONE}
		titanium-1.16.3-3.1.0.jar Titanium {titanium@3.1.0 DONE}
		SilentLib-1.16.3-4.8.1+61.jar Silent Lib {silentlib@4.8.1+61 DONE}
		AzureDoom-Chunk-Loader-1.16.3-1.0.0.jar Azuredooms Chunk Loader Mod {chunk@1.16.3-1.0.0 DONE}
		Lollipop-1.16.3-3.2.0.jar Lollipop {lollipop@3.2.0 DONE}
		forbidden_arcanus-1.16.3-1.0.1.jar Forbidden & Arcanus {forbidden_arcanus@1.16.3-1.0.1 DONE}
		jeiintegration_1.16.3-6.0.0.8.jar JEI Integration {jeiintegration@6.0.0.8 DONE}
		portality-1.16.3-3.1.1.jar Portality {portality@3.1.1 DONE}
		curios-forge-1.16.3-4.0.2.0.jar Curios API {curios@1.16.3-4.0.2.0 DONE}
		Botania-1.16.2-406.jar Botania {botania@1.16.2-406 DONE}
		Patchouli-1.16.2-44.jar Patchouli {patchouli@1.16.2-44 DONE}
		Xaeros_Minimap_20.24.0_Forge_1.16.3.jar Xaero's Minimap {xaerominimap@20.24.0 DONE}
		pamhc2foodcore-1.16.3-1.0.0.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		gravestone-1.16.3-1.0.2.jar Gravestone Mod {gravestone@1.16.3-1.0.2 DONE}
		ftb-backups-2.1.1.6.jar FTB Backups {ftbbackups@2.1.1.6 DONE}
		FastWorkbench-1.16.3-4.4.0.jar FastWorkbench {fastbench@4.4.0 DONE}
		polymorph-forge-1.16.3-0.15.jar Polymorph {polymorph@1.16.3-0.15 DONE}
		ftb-ultimine-1.1.0.10.jar FTB Ultimine {ftbultimine@1.1.0.10 DONE}
		FastFurnace-1.16.3-4.3.0.jar FastFurnace {fastfurnace@4.3.0 DONE}
		AppleSkin-mc1.16.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		AI-Improvements-1.16.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		refinedstorageaddons-0.7.2.jar Refined Storage Addons {refinedstorageaddons@0.7.2 DONE}
		FastLeafDecay-v25.jar FastLeafDecay {fastleafdecay@v25 DONE}
		WailaHarvestability-mc1.16.2-forge-1.1.13.jar Waila Harvestability {wailaharvestability@1.1.13 DONE}
		BetterAdvancements-1.16.3-0.1.0.102.jar Better Advancements {betteradvancements@0.1.0.102 DONE}
	Crash Report UUID: 4514e0d3-3e9d-4961-a0da-5467db4b6d81
	Patchouli open book context: n/a
	Player Count: 1 / 8; [ServerPlayerEntity['AnonymousDonald'/391, l='ServerLevel[New World]', x=68.23, y=68.00, z=262.93]]
	Data Packs: resourcefulbees:internals, vanilla, mod:cucumber, mod:trashslot (incompatible), mod:aiotbotania (incompatible), mod:curiousshulkerboxes, mod:jei, mod:uppers (incompatible), mod:mekanism, mod:mcwwindows (incompatible), mod:silents_mechanisms (incompatible), mod:reap, mod:rsgauges, mod:invtweaks (incompatible), mod:bettercaves (incompatible), mod:waystones (incompatible), mod:forgeendertech, mod:clumps (incompatible), mod:xaeroworldmap, mod:ctm (incompatible), mod:cookingforblockheads (incompatible), mod:placebo (incompatible), mod:comforts (incompatible), mod:powah, mod:curioofundying, mod:bookshelf, mod:botanypots, mod:xreliquary (incompatible), mod:uteamcore, mod:randompatches (incompatible), mod:darkutils (incompatible), mod:apotheosis (incompatible), mod:mcwdoors, mod:morpheus (incompatible), mod:mekanismgenerators, mod:waila, mod:wawla, mod:maessentials (incompatible), mod:jeresources, mod:forge, mod:mysticalagradditions (incompatible), mod:refinedstorage, mod:mysticalagriculture, mod:craftingtweaks (incompatible), mod:mcwbridges (incompatible), mod:industrialforegoing (incompatible), mod:usefulbackpacks, mod:resourcefulbees (incompatible), mod:titanium (incompatible), mod:silentlib (incompatible), mod:chunk (incompatible), mod:lollipop, mod:forbidden_arcanus (incompatible), mod:jeiintegration, mod:portality (incompatible), mod:curios, mod:botania, mod:patchouli (incompatible), mod:xaerominimap, mod:pamhc2foodcore (incompatible), mod:gravestone, mod:ftbbackups (incompatible), mod:fastbench (incompatible), mod:polymorph (incompatible), mod:ftbultimine (incompatible), mod:fastfurnace (incompatible), mod:appleskin, mod:aiimprovements, mod:refinedstorageaddons, mod:fastleafdecay (incompatible), mod:wailaharvestability, mod:betteradvancements
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.3_HD_U_G3
	OptiFine Build: 20200916-082411
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: ComplementaryShaders_3.05.zip
	OpenGlVersion: 4.6.0 NVIDIA 455.28
	OpenGlRenderer: GeForce RTX 2070 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16
```

**Comment by Cyco12** [comment]
To add onto @AnonymousDonald 's post, I'm experiencing this issue as well. Have not tested if we can reproduce it on single player, but we've experienced this crash twice on SMP.

The only way around preventing the server from crashing again has been wiping the affected player data and removing the affected teleporters.

Log file here: https://pastebin.com/w2YW4H2e

**Comment by MypowerHD** [comment]
Hey Ho, same as @Cyco12 we run into the same issue.
We are using All The Mods 6, @Cyco12, @AnonymousDonald you too?

Crash Report: https://pastebin.com/Dv3JLZxH
PlayerData Repo: https://github.com/MypowerHD/infected-playerdata-portality-crash

**Comment by Cyco12** [comment]
> Hey Ho, same as @Cyco12 we run into the same issue.
> We are using All The Mods 6, @Cyco12, @AnonymousDonald you too?
> 
> Crash Report: https://pastebin.com/Dv3JLZxH
> PlayerData Repo: https://github.com/MypowerHD/infected-playerdata-portality-crash

We were running ATM6 previously, but we're running a slightly different mod set now. It does have a lot of the same core mods though, I believe theres a list in the crashlog that I posted.

**Comment by AnonymousDonald** [comment]
We have a lot of the same mods as ATM, but wanted 1.16.3 server and it didn't have an updated version back then.

**Comment by Buuz135** [comment]
Forge Issue should be fixed already
